# Form implementation generated from reading ui file 'new_login_screen.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1514, 752)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_14 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_14.setGeometry(QtCore.QRect(970, 660, 601, 80))
        self.widget_14.setObjectName("widget_14")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_14)
        self.label_8.setGeometry(QtCore.QRect(310, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(170, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.widget_13 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_13.setGeometry(QtCore.QRect(0, 660, 601, 80))
        self.widget_13.setObjectName("widget_13")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 40, 1371, 431))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 80px;\n"
"margin-bottom:0px;")
        self.widget_3.setObjectName("widget_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_2.setGeometry(QtCore.QRect(170, 239, 121, 71))
        self.widget_2.setStyleSheet("QWidget {\n"
"    border: 5px solid rgb(75, 57, 239);\n"
"    border-radius: 0 0 0 10px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:1px ;\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"font: 650 italic 12pt \"MS Shell Dlg 2\";")
        self.label_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border:1px ;\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"font: 650 italic 12pt \"MS Shell Dlg 2\";")
        self.label_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(560, 240, 571, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.cameraLabel_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.cameraLabel_2.setGeometry(QtCore.QRect(840, 50, 626, 626))
        self.cameraLabel_2.setStyleSheet("")
        self.cameraLabel_2.setText("")
        self.cameraLabel_2.setPixmap(QtGui.QPixmap("virtual-face.jpg"))
        self.cameraLabel_2.setObjectName("cameraLabel_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 380, 331, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 800 13pt \"MS Shell Dlg 2\";\n"
" font-weight: bold;\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1514, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Designed by The Project Team. v1.0.0"))
        self.label_7.setText(_translate("MainWindow", " © 2023-2024 The Project Team. All rights reserved."))
        self.label_3.setText(_translate("MainWindow", "CV-"))
        self.label_9.setText(_translate("MainWindow", "AMS"))
        self.label_4.setText(_translate("MainWindow", "Attendance Management system"))
